### ISSUE TITLE
How to add your offer to wants?

### ISSUE THREAD

**Issue by SoraV** [vrchivejson/vrchivejson#1]

**Comment by vrchivejson** [comment]
Just fork it and edit as needed, will check once in a while to merge to here

**Comment by TekkyNeko** [comment]
Given the restructure of the site, and how there is no longer a want.json file, is there any other way we could do this? like commenting on an issue, re implementing want.json, or something else?

**Comment by Nommiiee** [comment]
> Given the restructure of the site, and how there is no longer a want.json file, is there any other way we could do this? like commenting on an issue, re implementing want.json, or something else?

We are working restructure, if you wanna contribute, you can simply create a new folder wants then a JSON file in the data folder. We will update the repo whenever we have an update.

**Comment by TekkyNeko** [comment]
Alright will do, thanks
