### ISSUE TITLE
Will there be any changes to the site design?

### ISSUE THREAD

**Issue by SoraV** [vrchivejson/vrchivejson#3]

**Comment by vrchivejson** [comment]
Planning on remaking the site from scratch since the current site is way too laggy and eats lots of resources and bandwidth.. will try to update when I'm not busy

**Comment by SoraV** [comment]
So you're the only one working on this site?

**Comment by vrchivejson** [comment]
Late reply but yes, pretty much the only one working on the site's design, the files are from somewhere else
