### ISSUE TITLE
Missing download links and source for some of the assets

### ISSUE THREAD

**Issue by Nommiiee** [vrchivejson/vrchivejson#8]
Some of the assets are missing download and source links, and I would like to contribute in the re-building the website. So, hit me up if you are interested in doing so.

**Comment by vrchivejson** [comment]
would be better if you use the JSON file directly from this repo, since I'm planning on updating it about every 2 weeks, but it would be nice that someone is helping updating the site.

**Comment by vrchivejson** [comment]
Also changing the names of the names of the JSON files so its easier to understand, there is gonna be more assets added.
